[build]
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "#custom"
  command = "npm start"
  targetPort = 3000

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200